services:
  postgres:
    image: postgres:16
    container_name: sniff-n-frolic-pos
    restart: unless-stopped
    environment:
      POSTGRES_USER: snf
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sniff_n_frolic_pos
    ports:
      - "5432:5432"
    volumes:
      - sniff_n_frolic_pos_data:/var/lib/postgresql/data

volumes:
  sniff_n_frolic_pos_data: